#!/bin/bash

python -m virtualenv test-site-virtualenv-3.7.4-no-sys-pack

source test-site-virtualenv-3.7.4-no-sys-pack/bin/activate

pip freeze


deactivate

## Load the relevant modules needed for the job

module load python/3.7.4

##module load anaconda3/latest
##python -m pip install --upgrade pip
##pip install pandas --user
pip install pyarrow --user
pip3 install -U scikit-learn
pip3 install tqdm
pip3 install --upgrade tensorflow --user
pip install numpy scipy scikit-learn
##pip install ipython --user #not satisfied


##pip install numpy --user
##pip install scipy --user
pip3 install ptyprocess 
##pip install six --user
##pip install --upgrade patsy --user
pip3 install --upgrade tensorflow --user

pip3 install --upgrade keras --user
pip3 install PyWavelets 
pip3 install statsmodels
pip3 install matplotlib
pip3 install seaborn
pip3 install --user --install-option="--prefix=" -U scikit-learn
pip3 install signals



#pip3 install labelEncoder
